# Generated by Django 5.2.4 on 2025-08-05 13:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='rating',
            new_name='mood',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='date',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='emotion_tags',
            field=models.CharField(default='neutral', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
