# Generated by Django 5.2.4 on 2025-08-08 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_rename_rating_moodentry_mood_remove_moodentry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodentry',
            old_name='mood',
            new_name='angry',
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='emotion_tags',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='angry_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='disgust',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='disgust_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='fear',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='fear_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='happy',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='happy_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sad',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='sad_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='surprise',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='surprise_tag',
            field=models.CharField(default='neutral', max_length=50),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
